"""Generates src/decoder_powers.h: the 128-bit powers of five the loads() float parser multiplies by.

Each entry is 5**q for q in -342..308 scaled to 128 bits with the top bit set, truncated
for q >= 0 and rounded up for q < 0, as in Daniel Lemire's fast_float (Apache-2.0/MIT).
"""
from pathlib import Path

SMALLEST, LARGEST = -342, 308
DEST = Path(__file__).resolve().parents[1] / "src" / "decoder_powers.h"


def entries():
    for q in range(SMALLEST, 0):
        power5 = 5 ** -q
        z = 0
        while (1 << z) < power5:
            z += 1
        if q >= -27:
            c = 2 ** (z + 127) // power5 + 1
        else:
            c = 2 ** (2 * z + 128) // power5 + 1
            while c >= 1 << 128:
                c //= 2
        yield q, c
    for q in range(0, LARGEST + 1):
        power5 = 5 ** q
        while power5 < 1 << 127:
            power5 *= 2
        while power5 >= 1 << 128:
            power5 //= 2
        yield q, power5


def main():
    lines = [
        "/* Generated by tools/powers_of_five.py; do not edit. */",
        f"#define POWER_OF_FIVE_SMALLEST ({SMALLEST})",
        f"#define POWER_OF_FIVE_LARGEST ({LARGEST})",
        "static const uint64_t powers_of_five[][2] = {",
    ]
    for q, value in entries():
        assert 1 << 127 <= value < 1 << 128
        lines.append(f"    {{0x{value >> 64:016X}ULL, 0x{value & (1 << 64) - 1:016X}ULL}},  /* 5^{q} */")
    lines.append("};")
    DEST.write_text("\n".join(lines) + "\n")
    print(f"wrote {DEST}")


if __name__ == "__main__":
    main()
